name: Push Event message
on:
  push:
    branches: [ master, feature1]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: |
          echo "hello, changes been pushed/PR has been raised/closed"
          echo "Changes are pushed"
